---
- name: "Install packages"
  apt: name="{{ item }}"
  with_items: "{{ ccollect_packages }}"
- name: "Create /srv/ccollect/ccollect-run"
  template:
    src: run.j2
    dest: /srv/ccollect/ccollect-run
    owner: root
    group: root
    mode: 0755
- name: "Create /etc/systemd/system/ccollect-CONF_NAME.service"
  template:
    src: ccollect.service.j2
    dest: "/etc/systemd/system/ccollect-{{ ccollect_conf_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify: Enable ccollect timer
- name: "Create /etc/systemd/system/ccollect-CONF_NAME.timer"
  template:
    src: ccollect.timer.j2
    dest: "/etc/systemd/system/ccollect-{{ ccollect_conf_name }}.timer"
    owner: root
    group: root
    mode: 0644
  notify: Enable ccollect timer
